### PR TITLE
fix: tell the user there's no counting channels configured when using `/select` with no counting channels set up, and also in other commands requiring a counting channel

### LINKED ISSUE #920: tell the user there's no counting channels configured when using `/select` with no counting channels set up, and also in other commands requiring a counting channel
the very long SSIA

### PR DESCRIPTION
**Pull request by promise**
Fixes #920

### CODE REVIEW

File: src/handlers/mentionCommands.ts [hunk 1]
```diff
@@ -47,6 +47,8 @@ async function handleCommand(message: Message<true>, document: GuildDocument, ex
     command.debugLevel === DebugCommandLevel.Admin && !config.admins.includes(message.author.id)
   ) return reply("⛔ This command is not available.", message, existingReply).then(newReply => [message, newReply]);
 
+  if (command.requireSelectedCountingChannel && document.channels.size === 0) return reply("💥 No counting channel is set up in this server! Create a new one by using `/channels new` or link an existing one with `/channels link`.", message, existingReply).then(newReply => [message, newReply]);
```
Comment (djohts) [inline src/handlers/mentionCommands.ts]: maybe include docs link here as well for consistency?

**Review by djohts — CHANGES_REQUESTED** [review]

File: src/handlers/mentionCommands.ts (hunk 1 above)
Comment (promise) [reply src/handlers/mentionCommands.ts]: I thought about it but didn't include it here because of markdown 🤷‍♂️

if others say the same thing then we can add it as a plain url

**Review by lacuna-exe — APPROVED** [review]

**Review by djohts — APPROVED** [review]

**Review by aditya20-b — APPROVED** [review]
LGTM

File: src/constants/autocompletes/countingChannels.ts [hunk 2]
```diff
@@ -9,6 +9,13 @@ const autocomplete: Autocomplete = {
     const search = String(query);
 
     const countingChannels = Array.from(document.channels.entries());
+    if (!countingChannels.length) {
```
Comment (wrac4242) [inline src/constants/autocompletes/countingChannels.ts:12]: maybe change to == 0, as practically its the same, but is syntactically more clear what you are trying

File: src/handlers/interactions/chatInputCommands.ts [hunk 3]
```diff
@@ -34,6 +35,8 @@ export default async function chatInputCommandHandler(interaction: ChatInputComm
     const countingChannel = document.channels.get(interaction.channelId);
     if (command.disableInCountingChannel && countingChannel) return void interaction.reply({ content: "❌ This command is disabled in counting channels.", ephemeral: true });
 
+    if (command.requireSelectedCountingChannel && document.channels.size === 0) return void interaction.reply({ content: `💥 No counting channel is set up in this server! Create a new one by using \`/channels new\` or link an existing one with \`/channels link\`. New to Countr? Check out the [documentation](<${docsUrl}>) to get started!`, ephemeral: true });
```
Comment (wrac4242) [inline src/handlers/interactions/chatInputCommands.ts:38]: this is the 3rd instance of this interaction text setup, refactor into a single file of reused messages?

**Review by wrac4242 — CHANGES_REQUESTED** [review]

File: src/handlers/interactions/chatInputCommands.ts (hunk 3 above)
Comment (wrac4242) [reply src/handlers/interactions/chatInputCommands.ts:38]: however, that is not blocking atm as people are experiencing this error in the wild

Comment (promise) [reply src/handlers/interactions/chatInputCommands.ts:38]: logic is different in all three different places, and also not a priority atm

**Review by wrac4242 — APPROVED** [review]
lgtm
